# Generated by Django 5.0.4 on 2024-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Veterinary Clinic', 'Veterinary Clinic'), ('Pet Training Services', 'Pet Training Services'), ('Pet Supply Stores', 'Pet Supply Stores'), ('Animal Control and Shelters', 'Animal Control and Shelters'), ('Pet-friendly Parks and Trails', 'Pet-friendly Parks and Trails'), ('Lost and Found Resources', 'Lost and Found Resources'), ('Rehoming Resources', 'Rehoming Resources'), ('Wildlife Resources', 'Wildlife Resources'), ('Human Help', 'Human Help')], default='Veterinary Clinic', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
